name = "MVFA"
uuid = "0121ec4e-bc64-11ee-28c6-59d8e973708d"
authors = ["Hang.W"]
version = "0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b1b6-d8193f3e49c0"
LinearAlgebra = "27e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DataFrames = "1"
julia = "1"
